runtime: php 
env: flex 
runtime_config: 
    document_root: . 
env_variables: 
    APP_LOG: errorlog 
    GOOGLE_STORAGE_BUCKET: "cs348demo-266020.appspot.com" 
    MYSQL_USER: "root" 
    MYSQL_PASSWORD: "password" 
    MYSQL_DSN: "mysql:dbname=workify-db;unix_socket=/cloudsql/cs348demo-266020:us-central1:workify-db" 
beta_settings: 
    cloud_sql_instances: "cs348demo-266020:us-central1:workify-db"
