LOAD DATA LOCAL INFILE 'tabApplicants.txt'
INTO TABLE Applicant COLUMNS TERMINATED BY '\t';

LOAD DATA LOCAL INFILE 'tabApplied.txt'
INTO TABLE Applied COLUMNS TERMINATED BY '\t';

LOAD DATA LOCAL INFILE 'tabCompanies.txt'
INTO TABLE Company COLUMNS TERMINATED BY '\t';

LOAD DATA LOCAL INFILE 'tabJobs.txt'
INTO TABLE Job COLUMNS TERMINATED BY '\t';
